static_presets = [
    {'name': 'Generation (TWh)', 'result': 'Generation (TWh)', 'preset': 'Stacked Bars'},
    {'name': 'Gen Frac', 'config': {'result':'Generation (TWh)', 'chart_type':'Line', 'x':'year', 'y':'Generation (TWh)', 'series':'tech', 'explode':'scenario', 'adv_op':'Ratio', 'adv_col':'tech', 'adv_col_base':'Total', 'filter': {}}},
    {'name': 'Final Gen by timeslice (GW)', 'result': 'Gen by m (GW)', 'preset': 'Stacked Bars Final'},
    {'name': 'Capacity (GW)', 'result': 'Capacity (GW)', 'preset': 'Stacked Bars'},
    {'name': 'New Capacity (GW)', 'result': 'New Capacity (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Cost/Value Streams (Billion $)', 'config': {'meta_map_tech':r'', 'meta_style_tech':r'', 'result':'Tech Value Streams', 'chart_type':'Bar', 'x':'year', 'y':'Bil $', 'series':'val_stream_type', 'explode':'tech', 'explode_group':'scenario', 'sync_axes':'No', 'bar_width':r'1.75', 'filter': {'tech':['battery','gas-cc-nsp','gas-ct-nsp','upv', 'dupv','wind-ons'], }}},
    {'name': 'Cost/Value Streams ($/MWh)', 'config': {'meta_map_tech':r'', 'meta_style_tech':r'', 'result':'Tech Value Streams', 'chart_type':'Bar', 'x':'year', 'y':'$/MWh', 'y_agg':'Weighted Ave', 'y_weight':'MWh', 'series':'val_stream_type', 'explode':'tech', 'explode_group':'scenario', 'bar_width':r'1.75', 'filter': {'tech':['upv','dupv','wind-ons'], }}},
    {'name': 'Energy Value Range ($/MWh)', 'config': {'meta_map_tech':r'', 'meta_style_tech':r'', 'result':'Tech Value Streams', 'range':'Within Series', 'x':'year', 'y':'$/MWh', 'y_agg':'Weighted Ave', 'y_weight':'MWh', 'series':'val_stream_type', 'explode':'tech', 'explode_group':'scenario', 'bar_width':r'1.75', 'filter': {'tech':['dupv','upv','wind-ons'], 'val_stream_type':['load_pca'], }}},
    {'name': 'Ave Cost/Value Streams ($/MWh)', 'config': {'meta_map_tech':r'', 'meta_style_tech':r'', 'result':'Tech Value Streams', 'chart_type':'Bar', 'x':'scenario', 'y':'$/MWh', 'y_agg':'Weighted Ave', 'y_weight':'MWh', 'series':'val_stream_type', 'explode':'tech', 'filter': {'tech':['dupv','upv','wind-ons'], 'year': {'start':2020}, }}},
    {'name': 'Load Marginals by Timelsice ($/MWh)', 'config': {'result':'Value Streams', 'chart_type':'Line', 'x':'year', 'y':'marginal', 'y_agg':'Weighted Ave', 'y_weight':'quantity', 'series':'scenario', 'explode':'m', 'sync_axes':'No', 'filter': {'val_stream_type':['load_pca'], }}},
    {'name': 'Final Duration curves', 'config': {'meta_map_tech':r'', 'meta_style_tech':r'', 'result':'Gen by m (GW)', 'chart_type':'Bar', 'x':'m', 'y':'Generation (GW)', 'explode':'tech', 'explode_group':'scenario', 'sync_axes':'No', 'x_min':r'0', 'x_max':r'8760', 'y_min':r'0', 'bar_width':r'c', 'filter': {'tech':['dupv','reqt','upv','wind-ons'], 'year':'last', }}},
    {'name': 'Value Factors', 'result': 'New Tech Value Factors', 'preset': 'Tech Value Factors', 'config': {'meta_map_tech':r'', 'meta_style_tech':r'', 'filter': {'tech':['dupv','reqt','upv','wind-ons'],}}},
]
