static_presets = [
    {'name': 'Base Generation (TWh)', 'result': 'Generation (TWh)', 'preset': 'Stacked Bars'},
    {'name': 'Generation Diff (TWh)', 'result': 'Generation (TWh)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Base Capacity (GW)', 'result': 'Capacity (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Capacity Diff (GW)', 'result': 'Capacity (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Base New Capacity (GW, 2-year)', 'result': 'New Capacity (GW)', 'preset': 'Stacked Bars'},
    {'name': 'New Capacity Diff (GW, 2-year)', 'result': 'New Capacity (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Jobs (millions)', 'result': 'JEDI Outputs', 'preset': 'Total Jobs'},
    {'name': 'Jobs Diff (millions)', 'result': 'JEDI Outputs', 'preset': 'Total Jobs', 'modify': 'diff'},
    {'name': 'Jobs (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Tech'},
    {'name': 'Jobs Diff (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Tech', 'modify': 'diff'},
    {'name': 'Earnings (Billion 2015$)', 'result': 'JEDI Outputs', 'preset': 'Stacked Earnings By Tech'},
    {'name': 'Earnings Diff (Billion 2015$)', 'result': 'JEDI Outputs', 'preset': 'Stacked Earnings By Tech', 'modify': 'diff'},
    {'name': 'Output (Billion 2015$)', 'result': 'JEDI Outputs', 'preset': 'Stacked Output By Tech'},
    {'name': 'Output Diff (Billion 2015$)', 'result': 'JEDI Outputs', 'preset': 'Stacked Output By Tech', 'modify': 'diff'},
    {'name': 'Value Add (Billion 2015$)', 'result': 'JEDI Outputs', 'preset': 'Stacked Value Add By Tech'},
    {'name': 'Value Add Diff (Billion 2015$)', 'result': 'JEDI Outputs', 'preset': 'Stacked Value Add By Tech', 'modify': 'diff'},
    {'name': 'Jobs (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Directness'},
    {'name': 'Jobs Diff (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Directness', 'modify': 'diff'},
    {'name': 'Jobs (millions)', 'result': 'JEDI Outputs', 'preset': 'Jobs By Directness'},
    {'name': 'Jobs Diff (millions)', 'result': 'JEDI Outputs', 'preset': 'Jobs By Directness', 'modify': 'diff'},
    {'name': 'Jobs (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Directness Explode Tech'},
    {'name': 'Jobs Diff (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Directness Explode Tech', 'modify': 'diff'},
    {'name': 'Jobs (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Category'},
    {'name': 'Jobs Diff (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Category', 'modify': 'diff'},
    {'name': 'Jobs (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Category Explode Tech'},
    {'name': 'Jobs Diff (millions)', 'result': 'JEDI Outputs', 'preset': 'Stacked Jobs By Category Explode Tech', 'modify': 'diff'},
    {'name': 'Average Onsite Jobs 2017-2050', 'result': 'JEDI Outputs', 'preset': 'Average Onsite Jobs Map 2017-2050'},
    {'name': 'Average Onsite Jobs 2017-2050 Diff', 'result': 'JEDI Outputs', 'preset': 'Average Onsite Jobs Map 2017-2050', 'modify': 'diff'},
    {'name': 'Average Onsite Renewable Jobs 2017-2050', 'result': 'JEDI Outputs', 'preset': 'Average Onsite Jobs Map 2017-2050', 'config':{'filter':{'jedi_tech':['wind','upv']}}},
    {'name': 'Average Onsite Renewable Jobs 2017-2050 Diff', 'result': 'JEDI Outputs', 'preset': 'Average Onsite Jobs Map 2017-2050', 'modify': 'diff', 'config':{'filter':{'jedi_tech':['wind','upv']}}},
    {'name': 'Average Onsite Fossil Jobs 2017-2050', 'result': 'JEDI Outputs', 'preset': 'Average Onsite Jobs Map 2017-2050', 'config':{'filter':{'jedi_tech':['coal','gas']}}},
    {'name': 'Average Onsite Fossil Jobs 2017-2050 Diff', 'result': 'JEDI Outputs', 'preset': 'Average Onsite Jobs Map 2017-2050', 'modify': 'diff', 'config':{'filter':{'jedi_tech':['coal','gas']}}},
]
