static_presets = [
    {'name': 'Generation (TWh)', 'result': 'Generation BA (TWh)', 'preset': 'Stacked Bars'},
    {'name': 'Generation Diff (TWh)', 'result': 'Generation BA (TWh)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Capacity Diff (GW)', 'result': 'Capacity BA (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'New Annual Capacity (GW)', 'result': 'New Annual Capacity BA (GW)', 'preset': 'Stacked Bars'},
    {'name': 'New Annual Capacity Diff (GW)', 'result': 'New Annual Capacity BA (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Annual Retirements (GW)', 'result': 'Annual Retirements BA (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Annual Retirements Diff (GW)', 'result': 'Annual Retirements BA (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Final Gen by timeslice (GW)', 'result': 'Gen by timeslice national (GW)', 'preset': 'Stacked Bars Final'},
    {'name': 'Final Gen by timeslice Diff (GW)', 'result': 'Gen by timeslice national (GW)', 'preset': 'Stacked Bars Final', 'modify': 'diff'},
    {'name': 'National Energy Price ($/MWh)', 'result': 'Energy Price National ($/MWh)', 'preset': 'Scenario Lines Over Time'},
    {'name': 'National Energy Price Diff ($/MWh)', 'result': 'Energy Price National ($/MWh)', 'preset': 'Scenario Lines Over Time', 'modify': 'diff'},
    {'name': 'System Cost (Billion $)', 'result': 'Sys Cost (Bil $)', 'preset': 'Stacked Bars'},
    {'name': 'System Cost Diff (Billion $)', 'result': 'Sys Cost (Bil $)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'CO2 Emissions National (MMton)', 'result': 'CO2 Emissions National (MMton)', 'preset': 'Scenario Lines Over Time'},
    {'name': 'CO2 Emissions National Diff (MMton)', 'result': 'CO2 Emissions National (MMton)', 'preset': 'Scenario Lines Over Time', 'modify': 'diff'},
    {'name': 'Final Wind Capacity (GW)', 'result': 'Capacity Resource Region (GW)', 'preset': 'RR Map Final Wind'},
    {'name': 'Final Wind Capacity Diff (GW)', 'result': 'Capacity Resource Region (GW)', 'preset': 'RR Map Final Wind', 'modify': 'diff'},
    {'name': 'Final Regional Energy Price (2015$/MWh)', 'result': 'Energy Price BA ($/MWh)', 'preset': 'Final BA Map'},
    {'name': 'Final Regional Energy Price Diff (2015$/MWh)', 'result': 'Energy Price BA ($/MWh)', 'preset': 'Final BA Map', 'modify': 'diff'},
]