static_presets = [
    {'name': 'Generation (TWh)', 'result': 'Generation (TWh)', 'preset': 'Stacked Bars'},
    {'name': 'Generation Diff (TWh)', 'result': 'Generation (TWh)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Capacity (GW)', 'result': 'Capacity (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Capacity Diff (GW)', 'result': 'Capacity (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'New Capacity (GW)', 'result': 'New Capacity (GW)', 'preset': 'Stacked Bars'},
    {'name': 'New Capacity Diff(GW)', 'result': 'New Capacity (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Retirements (GW)', 'result': 'Retirements (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Retirements Diff(GW)', 'result': 'Retirements (GW)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Final Gen by m (GW)', 'result': 'Gen by m national (GW)', 'preset': 'Stacked Bars Final'},
    {'name': 'Final Gen by m Diff (GW)', 'result': 'Gen by m national (GW)', 'preset': 'Stacked Bars Final', 'modify': 'diff'},
    {'name': 'CO2 Emissions (MMton)', 'result': 'Emissions, Fuel, Prices', 'preset': 'CO2 Emissions (MMton)'},
    {'name': 'CO2 Emissions Diff (MMton)', 'result': 'Emissions, Fuel, Prices', 'preset': 'CO2 Emissions (MMton)', 'modify': 'diff'},
    {'name': 'Elec Price ($/MWh)', 'result': 'Elec Price ($/MWh)', 'preset': 'National'},
    {'name': 'Elec Price Diff ($/MWh)', 'result': 'Elec Price ($/MWh)', 'preset': 'National', 'modify': 'diff'},
    {'name': 'Dereg Elec Price ($/MWh)', 'result': 'Dereg Elec Price ($/MWh)', 'preset': 'Stacked Bars'},
    {'name': 'Dereg Elec Price Diff ($/MWh)', 'result': 'Dereg Elec Price ($/MWh)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'System Cost (Bil $)', 'result': 'Sys Cost (Bil $)', 'preset': 'Stacked Bars'},
    {'name': 'System Cost Diff (Bil $)', 'result': 'Sys Cost (Bil $)', 'preset': 'Stacked Bars', 'modify': 'diff'},
    {'name': 'Final Wind Capacity (GW)', 'result': 'Capacity (GW)', 'preset': 'State Map Final Wind'},
    {'name': 'Final Wind Capacity Diff (GW)', 'result': 'Capacity (GW)', 'preset': 'State Map Final Wind', 'modify': 'diff'},
    {'name': 'Final Solar Capacity (GW)', 'result': 'Capacity (GW)', 'preset': 'State Map Final Solar'},
    {'name': 'Final Solar Capacity Diff (GW)', 'result': 'Capacity (GW)', 'preset': 'State Map Final Solar', 'modify': 'diff'},
]
